name: Build and deploy container app to Azure Web App - all-india-cart

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.AzureAppService_ContainerUsername_73a899443a7444be928f91658c91842a }}
          password: ${{ secrets.AzureAppService_ContainerPassword_e18873e201eb4d0684621446b94bfde9 }}

      - name: Build and push container image to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.AzureAppService_ContainerUsername_73a899443a7444be928f91658c91842a }}/all-india-cart:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "all-india-cart"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_ea05363d560c48d5bbe13c3aa6ca37e3 }}
          images: "index.docker.io/${{ secrets.AzureAppService_ContainerUsername_73a899443a7444be928f91658c91842a }}/all-india-cart:${{ github.sha }}"
